name: tool
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  charcode: ^1.1.3
  glob: ^2.0.2
  markdown: ^4.0.1
  mime_type: ^1.0.0
  mustache_template: ^2.0.0
  path: ^1.7.0
  pool: ^1.4.0
  sass: ^1.26.5
  shelf: ^1.2.0
  string_scanner: ^1.0.5
